Add expandable error messages + more (Alt to PR #1)
PretendoNetwork/Bandwidth pull request #2
Opened 2022-11-08 09:01 UTC by hauntii

This PR adds the following to Bandwidth:

- Collapsed errors that can be expanded by a button press, which auto-collapse after 45 seconds. ( They can be expanded at any time, even if the bot restarts. )

![expandable-errors](https://user-images.githubusercontent.com/57009359/200520238-0d67f7ec-8fce-45a6-9c94-cae7869aecaa.gif)

- Changed the automatic member counter to be updated every five minutes, rather than on join, to prevent ratelimiting if too many accounts were to join / leave at the same time.
- Moved util.js into the new `utils` folder as `timed.js`.
- Refactored the messageCreate.js to split out the error code functions into a utility in the `utils` folder. This is done to simplify adding more events, along with allowing the expandable errors to function without a circular loop.

2022-11-08 10:01 UTC, jonbarrow commented
Gave it a glance before work, will do a more in-depth review later today

Looks really good so far! I like the collapsing a lot

My only 2 areas of concern right now are the error code embed color and the timers for them to auto collapse again

It feels a bit odd to have the embed color initially be the color for the WiiU errors, makes it seem like the error is going to be a WiiU error? Maybe swap it out for our general brand color, 0x131733, initially before it gets expanded to show its console color. Or have the initial color _be_ the consoles color

I also see that situations where someone has an expanded error and the bot restarts isn't handled. If someone expands the error, and the bot restarts for whatever reason, then their emebed will never collapse again. Usually to handle these situations I also store active timers in a database with their end times and any relevant data (like in this case the message ID), and then on boot going through them all and self-recovering. Though that might be a bit over kill here since we'd be storing potentially thousands of rows of the DB just for 45 second timers. What do you think?

2022-11-08 10:17 UTC, hauntii commented
On the embed color, I've decided to switch it to the color for the said error, as that provides a better preview.

For the timer issues while rebooting, I don't think it's necessary to keep them saved as it isn't *too* important to have them forcefully collapse. It's also a pretty rare situation for that to occur, so I don't think it's enough to worry about.

2022-11-08 15:04 UTC, CirnoMoment commented
Clearly a 1/10 bot, doesn't even have an owo command, the most important part of the bot, without it, it's nothing😤😤😤. Also maybe have a second button to say "remove error" or something like that, just in case of false positives, as we have seen before in several cases now.

2022-11-08 23:26 UTC, hauntii commented
I've whipped up some less placeholder-y images for some of the embeds, and I'm unsure if I should just add these on to this PR, or create a new one. 

<details>
  <summary>Newer images</summary>
  
  ![accepted](https://user-images.githubusercontent.com/57009359/200696924-a68e3d10-8df4-439c-a311-3d7ad684b2be.png)
  ![denied](https://user-images.githubusercontent.com/57009359/200696925-36006344-8815-4f06-b193-a312cdf1c52c.png)
  ![pending](https://user-images.githubusercontent.com/57009359/200697438-93a133cc-4d16-4efe-9307-25fec903f5a0.png)
  ![piracy](https://user-images.githubusercontent.com/57009359/200697328-d01d3064-afc7-4242-866a-bbd091094712.png)

</details>

Which do you prefer I do, @jonbarrow ?

2022-11-09 11:18 UTC, jonbarrow requested changes
Reviewed the PR, looks really good! Only a few small changes for more consistent code is all

2022-11-09 11:18 UTC, jonbarrow commented on src/events/messageCreate.js
> +const checkForErrorCode = require('../utils/errorCode').checkForErrorCode;
For consistencies sake this should be written  as `const { checkForErrorCode } = require('../utils/errorCode');`

2022-11-09 11:18 UTC, jonbarrow commented on src/buttons/expand-error.js
> +const checkForErrorCode = require("../utils/errorCode").checkForErrorCode;
For consistencies sake this should be written as `const { checkForErrorCode } = require('../utils/errorCode');`

2022-11-09 11:18 UTC, jonbarrow commented on src/setup-guild.js
> +const timedUtils = require('./utils/timed');
The `errorCode` utils function is imported directly and not the entire module, but `timed` imports the entire module and then uses the function with dot notation. This is inconsistent. Either `errorCode` needs to be imported as a whole module and use dot notation like here, or `timed` needs to import only the function with destructuring

2022-11-09 11:18 UTC, jonbarrow commented
> Which do you prefer I do, @jonbarrow ?

I would say make a new PR for these new images. Thank you for that

2022-11-09 16:09 UTC, hauntii commented
Should be all ready to merge :)

2022-11-09 16:12 UTC, jonbarrow commented
Looks awesome! Thanks a bunch!

2022-11-09 16:13 UTC, merged

2022-11-09 16:22 UTC, jonbarrow commented
Bot has been updated and deployed on the live server, you should now see these changes in action. I look forward to your next PR!